-keep class com.facebook.hermes.** { *; }
-keep class com.facebook.react.** { *; }
-dontwarn com.facebook.react.**
-dontwarn com.facebook.hermes.**
-keepattributes *Annotation*
-keep class com.swmansion.** { *; }
-keep class com.facebook.yoga.** { *; }
